// Settings for form validation
export const formSettings = {
  inputSelector: ".popup__input",
  submitButtonSelector: ".popup__submit-button",
  inactiveButtonClass: "popup__submit-button_inactive",
  inputErrorClass: "popup__input_error",
  errorClass: "popup__input-error-text_active",
};

// Selectors
export const selectors = {
  cardsContainer: ".cards",
  cardTemplate: "#card-template",
  card: ".card",
  cardName: ".card__name",
  cardImage: ".card__image",
  cardLikeButton: ".card__like-button",
  cardLikeButtonActiveClass: "card__like-button_clicked",
  cardLikeCount: ".card__like-count",
  cardDeleteButton: ".card__delete-button",
  cardDeleteButtonVisibleClass: "card__delete-button_visible",
  popupImage: ".popup_type_image",
  editAvatarPopup: ".popup_type_avatar",
  editProfilePopup: ".popup_type_edit",
  addCardPopup: ".popup_type_add",
  deleteCardPopup: ".popup_type_delete",
  popupForm: ".popup__form",
  popupInput: ".popup__input",
  submitButton: ".popup__submit-button",
  userName: ".profile__name",
  userAbout: ".profile__about",
  userAvatar: ".profile__avatar",
  userInfo: ".profile__info",
  editAvatarOverlay: ".profile__avatar-wrapper",
  editButton: ".profile__edit-button",
  addButton: ".profile__add-button",
  avatarFormName: "avatar-form",
  profileFormName: "profile-form",
  cardFormName: "card-form",
};
